# Generated by Django 5.1.7 on 2025-05-14 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rating",
            options={"ordering": ("id",)},
        ),
    ]
